name: Terminal Game Center Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/setup-python@v1
    - name: Install cpplint
      run: |
          python -m pip install --upgrade pip
          pip install cpplint==1.4.5
    - uses: actions/checkout@v2
    - name: lint
      run: make lint
    - name: make build
      run: make
